### ISSUE TITLE
Cannot create python template : Getting TemplateNotFound: conf\deployment.yml 

### ISSUE THREAD

**Issue by RajVishakh** [databrickslabs/dbx#152] opened 2022-02-03 05:31 UTC
## Current Behavior After entering all the details, Getting the below error and the template is not getting generated.
**jinja2.exceptions.TemplateNotFound: conf\deployment.yml
ERROR:cookiecutter.generate:Stopping generation because post_gen_project hook script didn't exit successfully**

## Context
Having just been introduced to this framework, I tried to download the template and get started with this basic tutorial. But it got stuck with this step 
## Your Environment Local machine

* dbx version used: **dbx                       0.3.2**
* Databricks Runtime version:

**Comment by renardeinside** [comment] 2022-02-03 06:37
Hi @RajVishakh , 

could you please provide the command you've used, as well as the output of this command?

**Comment by RajVishakh** [comment] 2022-02-03 06:53
Hi @renardeinside 
Command used : **dbx init -p --template=python_basic**

output : 

D:\dbx_sample>dbx init --template=python_basic
[dbx][2022-02-03 10:42:25.873] Configuring new project from template python_basic ⚙️
[dbx][2022-02-03 10:42:25.904] No template parameters were provided. Please follow the cookiecutter init dialogue to pass template parameters...
project_name [cicd-sample-project]: SampleProject
version [0.0.1]: 0.0.1
Select cloud:
1 - AWS
2 - Azure
3 - Google Cloud
Choose from 1, 2, 3 [1]: 2
Select cicd_tool:
1 - GitHub Actions
2 - Azure DevOps
3 - GitLab
Choose from 1, 2, 3 [1]: 2
project_slug [sampleproject]: sampleproject_slug
workspace_dir [/Shared/dbx/sampleproject_slug]: /Shared/dbx/sampleproject_slug
artifact_location [dbfs:/Shared/dbx/projects/sampleproject_slug]: dbfs:/Shared/dbx/projects/sampleproject_slug
profile [DEFAULT]: DEFAULT
[dbx][2022-02-03 10:43:19.641] Configuring new environment with name default
[dbx][2022-02-03 10:43:19.672] dbx directory is not present, creating it
[dbx][2022-02-03 10:43:19.688] Environment configuration successfully finished
Traceback (most recent call last):
  File "C:\Users\Raj\AppData\Local\Temp\tmplnlm3i0_.py", line 105, in <module>
    post_processor.process()
  File "C:\Users\Raj\AppData\Local\Temp\tmplnlm3i0_.py", line 98, in process
    PostProcessor.process_cloud_component(env)
  File "C:\Users\Raj\AppData\Local\Temp\tmplnlm3i0_.py", line 86, in process_cloud_component
    NamedTemplate(env, "conf/deployment.yml").render_and_write(parameters=PostProcessor.TEMPLATE_PARAMETERS)
  File "C:\Users\Raj\AppData\Local\Temp\tmplnlm3i0_.py", line 41, in render_and_write
    self.render(parameters)
  File "C:\Users\Raj\AppData\Local\Temp\tmplnlm3i0_.py", line 29, in render
    template = self._env.get_template(str(self._path))
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\jinja2\loaders.py", line 194, in get_source
    pieces = split_template_path(template)
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\jinja2\loaders.py", line 35, in split_template_path
    **raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: conf\deployment.yml
ERROR:cookiecutter.generate:Stopping generation because post_gen_project hook script didn't exit successfully**
Traceback (most recent call last):
  File "C:\Program Files\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\Scripts\dbx.exe\__main__.py", line 7, in <module>
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\dbx\commands\init.py", line 57, in init
    cookiecutter(str(renderable_template_path), extra_context=parameters, no_input=no_input)
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\cookiecutter\main.py", line 101, in cookiecutter
    result = generate_files(
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\cookiecutter\generate.py", line 361, in generate_files
    _run_hook_from_repo_dir(
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\cookiecutter\generate.py", line 237, in _run_hook_from_repo_dir
    run_hook(hook_name, project_dir, context)
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\cookiecutter\hooks.py", line 131, in run_hook
    run_script_with_context(script, project_dir, context)
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\cookiecutter\hooks.py", line 115, in run_script_with_context
    run_script(temp.name, cwd)
  File "C:\Users\Raj\AppData\Roaming\Python\Python310\site-packages\cookiecutter\hooks.py", line 86, in run_script
    raise FailedHookException(
cookiecutter.exceptions.FailedHookException: Hook script failed (exit status: 1)

**Comment by renardeinside** [comment] 2022-02-03 08:49
Ah, I see - so it's something relevant to Windows, that's why I was unable to reproduce the issue. 
I'll take care of this one, thanks @RajVishakh !

**Comment by renardeinside** [comment] 2022-02-03 18:15
hey @RajVishakh , 
thanks a lot for raising the issue, it will be released in the 0.3.3 version

**Closed by renardeinside** 2022-02-03 18:15 UTC
Labels: bug
